In [1]:
from numpy import *

In [2]:
# 1. array()
arr = array ([1,2,3,4,5,6])
print(arr)
print(arr.dtype) #this command show the type of array
arr1= array ([1,2,3,4,5,6],float) # All the value converted in to float
print(arr1)
print(arr1.dtype)

[1 2 3 4 5 6]
int32
[1. 2. 3. 4. 5. 6.]
float64


In [3]:
#2.linspace(start,stop,step)

<br>
[step means the array divided in that parts like <br>
linspace(0,10,15),here 0 to 10 range will complete in 15 parts.<br>
if linspace(0,10) that means 0 to 10 range will complete in 50 parts.<br>
in linspace(0,20)means value start from 0 and end including 20.]<br>

In [4]:
arr2 = linspace(0,20,21)
print(arr2)
arr3 = linspace(0,20)
print(arr3)
# float to int convert:
ar = linspace(0,20,21)
ar = [int(a) for a in ar]
print(ar)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20.]
[ 0.          0.40816327  0.81632653  1.2244898   1.63265306  2.04081633
  2.44897959  2.85714286  3.26530612  3.67346939  4.08163265  4.48979592
  4.89795918  5.30612245  5.71428571  6.12244898  6.53061224  6.93877551
  7.34693878  7.75510204  8.16326531  8.57142857  8.97959184  9.3877551
  9.79591837 10.20408163 10.6122449  11.02040816 11.42857143 11.83673469
 12.24489796 12.65306122 13.06122449 13.46938776 13.87755102 14.28571429
 14.69387755 15.10204082 15.51020408 15.91836735 16.32653061 16.73469388
 17.14285714 17.55102041 17.95918367 18.36734694 18.7755102  19.18367347
 19.59183673 20.        ]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [5]:
# 3.arange(start,stop,step) [same as range]
arr4 = arange(2,20,2)
print(arr4)


[ 2  4  6  8 10 12 14 16 18]


In [6]:
# 4.logspace(start,stop,step)
a = logspace(2,10,10)
print(a)


[1.00000000e+02 7.74263683e+02 5.99484250e+03 4.64158883e+04
 3.59381366e+05 2.78255940e+06 2.15443469e+07 1.66810054e+08
 1.29154967e+09 1.00000000e+10]


In [7]:
# 5. zeros() [give float value]
arr5 = zeros(10)
print(arr5)
#for int value:
arr6 = zeros(10,int)
print(arr6)
# 6. ones() [give float value]
arr7 = ones(10)
print(arr7)
#for int value:
arr8 = ones(10,int)
print(arr8)
arr9 = 5*ones(10,int)
print(arr9)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]


for more example:<br>
https://www.w3schools.com/python/numpy/default.asp #(must visit)